language: python
python: 3.5
sudo: false
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=freeze

matrix:
  include:
    - os: osx
      # Using "generic" because osx in Travis doesn't support python
      language: generic
      env:
        - TOX_ENV=freeze

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+[\w\-]*$/

install:
  - "./.travis-workarounds.sh"
  - '[ "$TRAVIS_OS_NAME" != osx ] || source ~/virtualenv/python2.7/bin/activate'
  - pip install -U tox twine wheel codecov

script: tox -e $TOX_ENV

after_success:
  - codecov

before_deploy:
  - if [ $TOX_ENV == freeze ]; then tar -czf dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz -C dist_bin shub; fi

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: scrapinghub
    password:
      secure: CJWIRI51KvqZrkPf7At1li+bbAZ/pN3iWRUPy0JaKWAC8O8B+GljXQxiXisPyLL1pIikcfLYZScOsKEhE+Uon/beeL1TPimVU3ELr7GYzuIkl3eK7quFUOiJ7glEggA5UyGNmk6goMVgaBQEOwT3gwH2LYwd1uFRvQsgIPY+tks=
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: scrapinghub/shub
      condition: "$TRAVIS_OS_NAME == linux && $TOX_ENV == py35"
  - provider: releases
    api_key:
      secure: JE86/LwMlkUdLXhNe3bmVQPBo9tSDXDOfIM5q8oEmkKOPymQX/dahqw5T7GCQYZUK5M9a1hVeE4ano9xb6xBX2dxVkzBunPMQMaO/UZWtP5rxsmBMr0YLOERfuWeHBDlgW7gUILZYIa7V/Z0EsnAlpSZk5nJsYW/IlmXXWKNTL0=
    file: dist_bin/shub-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz
    skip_cleanup: true
    draft: true
    on:
      tags: true
      repo: scrapinghub/shub
      condition: "$TOX_ENV == freeze"
