language: python
python: 2.7
branches:
  only:
  - master
  - /^\d\.\d+$/
  - /^v\d\.\d+\.\d+(rc\d+|dev\d+)?$/
env:
- TOXENV=py27
install:
- pip install -U tox twine wheel codecov
script: tox
after_success:
- codecov
cache:
  directories:
  - $HOME/.cache/pip
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  on:
    tags: true
    condition: $TOXENV == py27 && $TRAVIS_TAG =~ ^v[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|dev[0-9]+)?$
  password:
    secure: eOGUfCqub/kFX3XGYBU1rQO94OeGK2n7oDj7aMhsi5++YXNx6bxDdUzbshHeRJCKHo0Gpay6aY8pPn4GYzqyAWpSf9YKFX2S42cpPVDfkF3LKUFSBcVuFFkafIfggqAQOKBighm5tmOho3VpIPkScTpOjHfRHiEtdX6wrfRXjg9bt/sQJk+y60SMRp7gZeifDTwzSmkNhJhtwGnZysCTpwrJ36xVkO9Ul0WNvtTNvRacj3/llpDy32+xJNuBOpe4ur+loW0gFM+vXGs9u1K8GgwomAEa4BLoBQAP4lW7Jt7lI2LuQV5xn5vBD1j21q0fWAdlTsSrqmOHG3LCJHBvHZ+1C/ztTGoXhEZRELW/2ZXVOHQ6pd0VtaBOzcgPlU6AldX382W2iMfgoKr/vh1wsKT8P4y4f704Yg9dV8a/utZUPAW/Eo9nL3UJFBQhpEbsLtRz9OBaAk/y0UUieQ6uQg6kClavbkIqkhjg++wNUYqcjZkUXxjJ5DZqZFFBJPPI2BOGeypNlF1AsTvGWNrlljdQXQQeLxLm5jUhSPGyz0o3r/soCu1od+KNXlbMJhOqC0uPV3WXZKyRjy/f/S/spJpjmKHXrJ8y7Ji6btjXMH5dV1WJcafZ/PYbUBsAWsnqE4bbFA60RX1yy+F76KjZaSN5NJTPUR8AZYFn6H256vM=
